<?php

define('path_1', 'MAM/Amma/');
define('path_2', 'MAM/Ashram_life/');
define('path_3', 'MAM/Senior_disciples/');
define('path_4', 'MAM/Ashram life/');
define('path_5', 'MAM/Amrita_Enterprises/Amrita_technologies/');
define('path_6', 'MAM/Amrita_Enterprises/pharmacy/');
define('path_7', 'MAM/Amrita_Enterprises/Amrita TV/');
define('path_8', 'MAM/Amrita_Enterprises/Amrita life/');
define('path_9', 'MAM/Amrita_Enterprises/Amrita optical/');
define('path_10', 'MAM/Amrita_Enterprises/Amrita publications/Amrita books/');
define('path_11', 'MAM/Amrita_Enterprises/Amrita publications/Audio/');
define('path_12', 'MAM/Amrita_Enterprises/Amrita publications/Video/');
define('path_13', 'MAM/Amrita_Enterprises/Amrita publications/Subscriptions/');
define('path_14', 'MAM/Amrita_Enterprises/Amrita publications/Amrita store/');
define('path_15', 'MAM/Empowerment/Ayudh/');
define('path_16', 'MAM/Empowerment/IAM/');
define('path_17', 'MAM/Empowerment/Amrita Yoga/');
define('path_18', 'MAM/Empowerment/Bala Samskriti/');
define('path_19', 'MAM/Empowerment/Amrita kudumbam/');
define('path_20', 'MAM/Empowerment/Other Annual Events/Geetamritam/');
define('path_21', 'MAM/Hospitals/Main Hospitals/Kochi/');
define('path_22', 'MAM/Hospitals/Main Hospitals/Delhi-NCR/');
define('path_23', 'MAM/Hospitals/Main Hospitals/Amaravati/');
define('path_24', 'MAM/Hospitals/Satellite Hospitals/Amritapuri/');
define('path_25', 'MAM/Hospitals/Satellite Hospitals/Mysuru/');
define('path_26', 'MAM/Hospitals/Satellite Hospitals/Kalpetta/');
define('path_27', 'MAM/Hospitals/Satellite Hospitals/Mumbai/');
define('path_28', 'MAM/Hospitals/Satellite Hospitals/pampa/');
define('path_29', 'MAM/Hospitals/Satellite Hospitals/Njarakal/');
define('path_30', 'MAM/Hospitals/Satellite Hospitals/Andaman/');
define('path_31', 'MAM/Hospitals/clinics/sivakasi/');
define('path_32', 'MAM/Hospitals/clinics/Bengaluru/');
define('path_33', 'MAM/Hospitals/Ayurveda Hospital/');
define('path_34', 'MAM/Disaster Relief/Disaster/SubFolder/');
define('path_35', 'MAM/Socail Welfare projects/Amrita Kuteeram/');
define('path_36', 'MAM/Socail Welfare projects/Vidyamritam/');
define('path_37', 'MAM/Socail Welfare projects/Amrita Nidhi/');
define('path_38', 'MAM/Socail Welfare projects/Amrita Chetana/');
define('path_39', 'MAM/Socail Welfare projects/Amala Bharatham campaign/');
define('path_40', 'MAM/Socail Welfare projects/Amrita see/');
define('path_41', 'MAM/Socail Welfare projects/A serve/');
define('path_42', 'MAM/Branches/Samiti/Satsang Group/');
define('path_43', 'MAM/Education/University/Campuses/Schools/Departments/SubFolders/');
define('path_44', 'MAM/Education/University/Campuses/Research centers/Projects/SubFolders/');
define('path_45', 'MAM/Education/University/Campuses/Support/Departments/SubFolders/');
define('path_46', 'MAM/Education/HE Institutions/Campuses/Schools/Departments/SubFolders/');
define('path_47', 'MAM/Education/HE Institutions/Campuses/Research centers/Projects/SubFolders/');
define('path_48', 'MAM/Education/HE Institutions/Campuses/Support/Departments/SubFolders/');
define('path_49', 'MAM/Education/schools/Aided/Schools/SubFolders/');
define('path_50', 'MAM/Education/schools/Private/Schools/SubFolders/');
define('path_51', 'MAM/Education/Other Educational Institutions/IAS Academy/MAM/centers/SubFolders/');
define('path_52', 'MAM/Education/Other Educational Institutions/ASHIS/centers/SubFolders/');
define('path_53', 'MAM/Education/Other Educational Institutions/AIDA/centers/SubFolders/');
define('path_54', 'MAM/Education/Other Educational Institutions/shilpa kala kshetra/centers/SubFolders/');
define('path_55', 'MAM/Education/Other Educational Institutions/Amrita ITI/centers/SubFolders/');

?>
